app            = "slsh-me"
primary_region = "cdg"

[build]

[deploy]
  release_command = "bin/deploy"

[env]
  APP_HOST                  = "slsh.me"
  PORT                      = "3000"
  RAILS_ENV                 = "production"
  RAILS_LOG_TO_STDOUT       = "true"
  RAILS_SERVE_STATIC_FILES  = "true"

[http_service]
  internal_port        = 3000
  force_https          = true
  auto_stop_machines   = "off"
  auto_start_machines  = true
  min_machines_running = 1
  processes            = ["app"]

  [http_service.concurrency]
    type       = "requests"
    hard_limit = 200
    soft_limit = 150

[[vm]]
  size   = "shared-cpu-1x"
  memory = "256mb"

[processes]
  app    = "bin/rails server -p 3000 -b 0.0.0.0"
  worker = "bin/jobs --mode=async"

[[restart]]
  policy = "always"
  processes = ["worker"]
